// This file was generated by Prisma. For Bun-based setup use:
// bun add -d prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI exclusively uses the direct connection to push schema changes
    url: process.env["DIRECT_URL"], 
  },
});