// This file was generated by Prisma. For Bun-based setup use:
// bun add -d prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations are applied manually via Supabase SQL editor (direct connection is IPv6-only on free tier).
    // Transaction pooler (DATABASE_URL) is used for prisma generate and migrate resolve.
    url: process.env["DATABASE_URL"],
  },
});