// This file was generated by Prisma. For Bun-based setup use:
// bun add -d prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // We apply migrations manually via Supabase SQL editor (direct connection is IPv6-only on free tier).
    // The transaction pooler works for prisma generate.
    // We use the session pooler (port 5432) for migrate commands to avoid IPv6 issues.
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});